services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ngrok-ml:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=2gv9k1JzoILrQz568I02o7imFg1_6iVKmrGJABNiHn8UFYtVa # Add your ngrok auth token here
    command: http --log=stdout  ml:8000
    depends_on:
      - ml
    networks:
      - default
