services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ngrok-ml:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} # Add your ngrok auth token here
    command: http --domain=sweet-frequently-cardinal.ngrok-free.app ml:8000
    depends_on:
      - ml
    networks:
      - default
